import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ChevronDown, ChevronUp } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

const FAQ = () => {
  const { t } = useTranslation();
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  
  // Create direct FAQ items with Excel AI and ExcelEasy keyword integration
  const faqItems: FAQItem[] = [
    {
      question: "What can I do with ExcelEasy AI tools?",
      answer: "ExcelEasy's AI tools let you create Excel spreadsheets from text descriptions, extract tables from images, get help with Excel formulas, generate charts, and automate repetitive Excel tasks. Our Excel AI solutions work with all Excel versions and require no login or installation."
    },
    {
      question: "Is ExcelEasy free to use?",
      answer: "Yes, all core Excel AI features on ExcelEasy are completely free. You can generate spreadsheets, convert images to Excel, create charts, and get formula help without any payment or registration required."
    },
    {
      question: "How accurate is the Excel AI image converter?",
      answer: "ExcelEasy's Excel AI image converter can extract data from clear, well-formatted tables with approximately 95-98% accuracy. The tool works best with clear images and structured tabular data, converting images directly to Excel format."
    },
    {
      question: "Can I use complex Excel formulas with ExcelEasy?",
      answer: "Yes! Our Excel AI understands and can help with advanced Excel formulas including VLOOKUP, INDEX/MATCH, SUMIFS, conditional formatting, pivot tables, and other complex spreadsheet functions."
    },
    {
      question: "Will ExcelEasy work with my version of Excel?",
      answer: "Yes, all Excel files generated by ExcelEasy AI are compatible with Microsoft Excel 2010 and newer, Google Sheets, LibreOffice Calc, and other major spreadsheet applications."
    },
    {
      question: "How do I get started with ExcelEasy?",
      answer: "Simply navigate to any Excel AI tool on our site, describe what you need, and our AI will generate the spreadsheet, formula, or chart. No registration or software installation is required to begin using Excel AI tools."
    }
  ];

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="py-16 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-gray-600 text-center mb-10">
            Quick answers about ExcelEasy's AI-powered Excel tools
          </p>

          <div className="space-y-4">
            {faqItems.map((item, index) => (
              <div 
                key={index} 
                className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden"
              >
                <button
                  className={`w-full text-left p-5 flex justify-between items-center focus:outline-none ${
                    openIndex === index ? 'bg-blue-50' : ''
                  }`}
                  onClick={() => toggleFaq(index)}
                >
                  <h3 className="text-lg font-medium pr-8">
                    {item.question}
                  </h3>
                  <span className="text-blue-500 flex-shrink-0">
                    {openIndex === index ? <ChevronUp /> : <ChevronDown />}
                  </span>
                </button>
                
                {openIndex === index && (
                  <div className="px-5 pb-5 text-gray-600">
                    {item.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
          
          <div className="text-center mt-10">
            <p className="text-sm text-gray-500">
              Can't find what you're looking for? <a href="/contact" className="text-blue-600 hover:underline">Contact our Excel AI support team</a>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQ; 